Homework 14/Homework 14/Models/DogViewModel.cs
namespace Homework_14.Models
{
    public class DogViewModel
    {
        public DogViewModel()
        {

        }

        public string PetName { get; set; }
        public string OwnerName { get; set; }
        public int PetAge { get; set; }
        public int PetWeight { get; set; }
    }
}

Homework 14/Homework 14/Models/ErrorViewModel.cs
using System;

namespace Homework_14.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Homework 14/Homework 14/Controllers/HomeController.cs
using Homework_14.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Homework_14.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Homework 14/Homework 14/Controllers/VetController.cs
using Microsoft.AspNetCore.Mvc;
using Homework_14.Models;
using System;

namespace Homework_14.Controllers
{
    public class VetController : Controller
    {
        [HttpGet]
        public IActionResult VetApplication()
        {
            ModelState.Clear();
            return View();
        }


        [HttpPost]
        public IActionResult VetApplication(DogViewModel dog)
        {
            Console.WriteLine($"Pet name: {dog.PetName}, age: {dog.PetAge}, weight: {dog.PetWeight}, owner: {dog.OwnerName}");
            return VetApplication();
        }
    }
}

Homework 14/Homework 14/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Homework_14</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Homework_14</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vet" asp-action="VetApplication">Register your pet</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Homework_14 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Homework 14/Homework 14/Views/Vet/VetApplication.cshtml
@model DogViewModel
@{
}
<form method="post">
    <div>
        <label>Pet name</label>
        <input asp-for="PetName"/>
    </div>
    <div>
        <label>Pet age</label>
        <input asp-for="PetAge"/>
    </div>
    <div>
        <label>Pet weight</label>
        <input asp-for="PetWeight"/>
    </div>
    <div>
        <label>Owner name</label>
        <input asp-for="OwnerName"/>
    </div>
    <button type="submit">Submit</button>
</form>